version: '3.8'

services:
  # Backend API
  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - MYSQL_SERVER=${MYSQL_SERVER}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-change-in-production}
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: unless-stopped

  # Backend Scraper (original functionality)
  backend-scraper:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - TZ=${TZ:-UTC}
      - DATABASE_URI=${DATABASE_URI}
      - MYSQL_SERVER=${MYSQL_SERVER}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - PUSHOVER_API_KEY=${PUSHOVER_API_KEY}
      - PUSHOVER_PRIORITY=${PUSHOVER_PRIORITY:-1}
      - PUSHOVER_SOUND=${PUSHOVER_SOUND}
      - RUN_SCHEDULE=${RUN_SCHEDULE:-01:00,05:00,09:00,13:00,17:00,21:00}
      - ENABLE_JAILS_CONTAINING=${ENABLE_JAILS_CONTAINING}
      - ON_DEMAND=${ON_DEMAND:-False}
      - HEARTBEAT_WEBHOOK=${HEARTBEAT_WEBHOOK}
      - FETCH_MUGSHOTS=${FETCH_MUGSHOTS:-False}
      - MUGSHOT_TIMEOUT=${MUGSHOT_TIMEOUT:-5}
    depends_on:
      - db
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend-api
    restart: unless-stopped

  # Database (MySQL)
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-incarceration_bot}
      - MYSQL_USER=${MYSQL_USERNAME:-bot_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-bot_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${MYSQL_USERNAME:-bot_user}
      - PMA_PASSWORD=${MYSQL_PASSWORD:-bot_password}
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  default:
    name: incarceration_bot_network
