services:
  incarceration_bot:
    image: justinkumpe/incarceration_bot:latest
    environment:
      # Database-agnostic configuration
      - DB_HOST=${DB_HOST:-172.16.21.10}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-jail_test}
      - DB_PASSWORD=${DB_PASSWORD:-LetmeN2it}
      - DB_NAME=${DB_NAME:-jail_test}
      - DB_TYPE=${DB_TYPE:-mysql}
      # Legacy MySQL environment variables for backwards compatibility
      - MYSQL_SERVER=${MYSQL_SERVER:-172.16.21.10}
      - MYSQL_USERNAME=${MYSQL_USERNAME:-jail_test}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-LetmeN2it}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-jail_test}
      - TZ=${TZ:-America/Chicago}
      - ON_DEMAND=${ON_DEMAND:-True}
      - ENABLE_JAILS_CONTAINING=${ENABLE_JAILS_CONTAINING:-so-ar,aiken-so-sc}
      - LOG_LEVEL=${LOG_LEVEL:-TRACE}
      - FETCH_MUGSHOTS=${FETCH_MUGSHOTS:-True}
      - MUGSHOT_TIMEOUT=${MUGSHOT_TIMEOUT:-5}
      # Pushover Configuration (empty to disable notifications)
      - PUSHOVER_API_KEY=${PUSHOVER_API_KEY:-}
      - PUSHOVER_PRIORITY=${PUSHOVER_PRIORITY:-1}
      - PUSHOVER_SOUND=${PUSHOVER_SOUND:-default}
    networks:
      - incarceration_network
    restart: unless-stopped

  backend_api:
    image: justinkumpe/incarceration_bot_api:latest
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      # Database-agnostic configuration
      - DB_HOST=${DB_HOST:-172.16.21.10}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-jail_test}
      - DB_PASSWORD=${DB_PASSWORD:-LetmeN2it}
      - DB_NAME=${DB_NAME:-jail_test}
      - DB_TYPE=${DB_TYPE:-mysql}
      # Legacy MySQL environment variables for backwards compatibility
      - MYSQL_SERVER=${MYSQL_SERVER:-172.16.21.10}
      - MYSQL_USERNAME=${MYSQL_USERNAME:-jail_test}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-LetmeN2it}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-jail_test}
      - TZ=${TZ:-America/Chicago}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-change-in-production}
    networks:
      - incarceration_network
    restart: unless-stopped

  frontend:
    image: justinkumpe/incarceration_bot_frontend:latest
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
      - VITE_APP_TITLE=${VITE_APP_TITLE:-Incarceration Bot Dashboard}
    depends_on:
      - backend_api
    networks:
      - incarceration_network
    restart: unless-stopped

networks:
  incarceration_network:
    driver: bridge
