name: Backend Scraper - Beta

on:
  push:
    branches: [Beta]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-scraper-beta.yml'

concurrency:
  group: backend-scraper-beta-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-backend-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: justinkumpe/incarceration_bot
          tags: |
            type=raw,value=latest-beta
            type=sha,prefix={{branch}}-
          
      - name: Build and Push Backend Scraper Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
