name: Push Docker Images to Docker Hub (Beta)

on:
  push:
    branches: Beta

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build and Push Backend Scraper Image
        run: |
            docker buildx build --push \
                --tag justinkumpe/incarceration_bot:latest-beta \
                --platform linux/amd64,linux/arm/v7,linux/arm64 \
                --file ./backend/Dockerfile ./backend
      
      - name: Build and Push Backend API Image
        run: |
            docker buildx build --push \
                --tag justinkumpe/incarceration_bot_api:latest-beta \
                --platform linux/amd64,linux/arm/v7,linux/arm64 \
                --file ./backend/Dockerfile.api ./backend
      
      - name: Build and Push Frontend Image
        run: |
            docker buildx build --push \
                --tag justinkumpe/incarceration_bot_frontend:latest-beta \
                --platform linux/amd64,linux/arm/v7,linux/arm64 ./frontend